name: kms-frontend
region: sgp1
ingress:
  rules:
    - match:
        path:
          prefix: /
      component:
        name: web
services:
  - name: web
    environment_slug: node-js
    source_dir: .
    build_command: npm ci && npm run build && cp -r public .next/standalone/public && cp -r .next/static .next/standalone/.next/static
    run_command: node .next/standalone/server.js
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    envs:
      - key: PORT
        scope: RUN_TIME
        value: "8080"
      - key: HOSTNAME
        scope: RUN_TIME
        value: "0.0.0.0"
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: NEXT_PUBLIC_API_URL
        scope: RUN_AND_BUILD_TIME
        value: https://uplbkain-backend-wygu3.ondigitalocean.app/api
      - key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
        scope: RUN_AND_BUILD_TIME
        value: 786829784177-pvntoed2n3g0t6u52j91v6n711k9cglc.apps.googleusercontent.com
